### PR TITLE
Make network layer consistent throughout e2e-test

### LINKED ISSUE #794: # of replicas for net-contour-controller not updated by v1alpha1.HighAvailability.Replicas
**Describe the bug**
Got a reconciliation timeout on the `test/e2e: TestKnativeServingDeployment` with a `contour` network after the update #749

```
    verify.go:301: Retrying...
    verify.go:300: deployment "net-contour-controller": Status.Replicas = 1, want: 2
    verify.go:301: Retrying...
    verify.go:300: deployment "net-contour-controller": Status.Replicas = 1, want: 2
    verify.go:301: Retrying...
    verify.go:308: Timed out waiting on KnativeServing to delete timed out waiting for the condition
    --- FAIL: TestKnativeServingDeployment/configure (354.50s)
```

```
$ kubectl get deploy -n knative-operator-testing
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
activator                2/2     2            2           3m53s
autoscaler               2/2     2            2           3m53s
autoscaler-hpa           2/2     2            2           3m50s
controller               2/2     2            2           3m53s
domain-mapping           2/2     2            2           3m52s
domainmapping-webhook    2/2     2            2           3m52s
net-contour-controller   1/1     1            1           3m50s
net-istio-controller     2/2     2            2           2m47s
net-istio-webhook        2/2     2            2           2m47s
webhook                  2/2     2            2           3m51s

```

Full log: https://storage.googleapis.com/knative-prow/logs/ci-knative-operator-s390x-e2e-tests/1442776110814203904/build-log.txt

**Expected behavior**
\# of replicas for `net-contour-controller` is also updated to 2 like other components under `KnativeServing`

**To Reproduce**
From a cleanly-installed k8s cluster,

```
$ export KO_DOCKER_REPO=localhost:5000
$ export INGRESS_CLASS=contour.ingress.networking.knative.dev
$ export KUBECONFIG=$HOME/.kube/config
$ kubectl create ns knative-serving
$ # istio only needed for `gateways.networking.istio.io` CRD 
$ kubectl apply -f https://github.com/knative-sandbox/net-istio/releases/download/v0.23.0/istio.yaml 2> /dev/null
$ kubectl apply -f https://raw.githubusercontent.com/knative/serving/main/third_party/contour-latest/contour.yaml
$ kubectl apply -f https://raw.githubusercontent.com/knative/serving/main/third_party/contour-latest/net-contour.yaml
$ kubectl wait --timeout=5m pod --for=condition=Ready -n contour-external -l '!job-name'
$ ./test/e2e-tests.sh --run-tests
```

**Knative release version**
main branch (1403d9c2dc27b32a2bff8e5e500acd0a05661779)

### PR DESCRIPTION
**Pull request by BbolroC**
Fixes #794 

## Proposed Changes

* Make a network layer consistent throughout the e2e test in a case where one other than `istio` is installed
* Configure `IngressConfigs` and `ConfigMapData` on creating or updating `KnativeServing` according to a value of the env `INGRESS_CLASS`
* Do nothing for istio

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by BbolroC** [comment]
@nak3 Could you review this if you have time? Thanks.

File: test/resources/knativeserving.go [hunk 1]
```diff
@@ -143,3 +123,38 @@ func getTestKSOperatorCRSpec() v1alpha1.KnativeServingSpec {
...
+	case "istio":
+		istioEnabled = true
+	case "contour":
+		contourEnabled = true
+	case "kourier":
+		kourierEnabled = true
+	}
+
+	if !istioEnabled {
+		(*ks).Spec.Ingress = &v1alpha1.IngressConfigs{
```
Comment (markusthoemmes) [inline test/resources/knativeserving.go:147]:
```suggestion
		ks.Spec.Ingress = &v1alpha1.IngressConfigs{
```

Not sure what the indirection is about here :thinking: (this applies to all occurences below)

Comment (BbolroC) [reply test/resources/knativeserving.go:147]: Thanks for the comment. Yeah, I am still trying to get myself familiar with Go. I will change the code based on the suggestion.

File: test/resources/verify.go [hunk 2]
```diff
@@ -150,6 +152,7 @@ func verifyEmptySpec(t *testing.T, loggingConfigMapName string, clients *test.Cl
 		t.Fatalf("Existing KS operator CR gone: %s", names.KnativeServing)
 	}
 	ks.Spec = v1alpha1.KnativeServingSpec{}
+	configureIngressClass(ks)
```
[the remark this answers is not in the document]
Comment (BbolroC) [reply test/resources/verify.go:155]: This is exactly what I expected for this PR. I was thinking that the order of the tests should be changed. But I will wait for other opinions.

File: test/resources/verify.go [hunk 3]
```diff
@@ -65,17 +65,18 @@ func KSOperatorCRVerifyConfiguration(t *testing.T, clients *test.Clients, names
...
 
 	// Now remove the config from the spec and update
 	verifyEmptySpec(t, loggingConfigMapName, clients, names)
-
-	// Verify HA config
-	VerifyHADeployments(t, clients, names)
 }
 
 func verifyDefaultConfig(t *testing.T, ks *v1alpha1.KnativeServing, defaultsConfigMapName string, clients *test.Clients, names test.ResourceNames) {
+	configureIngressClass(ks)
```
Comment (nak3) [inline test/resources/verify.go:79]: I think it is better to call `configureIngressClass()` in `getTestKSOperatorCRSpec()`. The `getTestKSOperatorCRSpec` sets the `ks.spec` for tests so we can align with it.

Comment (BbolroC) [reply test/resources/verify.go]: yeah, I agree. The feedback has been reflected. Thanks.
