### PR TITLE
Fix the error issue with installing spec.manifests

### LINKED ISSUE #741: No error message in `status` if the `spec.version` is not supported
**Describe the bug**
Operator version: v0.25.0
KnativeServing's `spec.version`: v0.21.0
There is error logs in operator controller, but error is not shown in CR's status.

**Expected behavior**
Show error log in CR's status.

**To Reproduce**
1. install knative-operator with version v0.25.0
2. apply KnativeServing with spec.version=0.21.0 and spec.manifests must not be nil
3. kubectl logs controller-pod-xxx...

**Knative release version**
v0.25.0

**Additional context**

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #741

If the spec.manifests is specified with an older version, not supported by the operator, the operator can still work by merely installing what is available in spec.manifests.

### CODE REVIEW

**Comment by houshengbo** [comment]
@charles-woshicai 
I tried to fix the issue like this.
spec.manifests with an older version should work.

File: pkg/reconciler/knativeeventing/source/source.go [hunk 1]
```diff
@@ -103,7 +98,16 @@ func getSourcePath(version string, ke *v1alpha1.KnativeEventing) string {
...
 	version := common.TargetVersion(instance)
 	sourcePath := getSourcePath(version, convertToKE(instance))
-	return getSource(manifest, sourcePath)
+	m, err := getSource(manifest, sourcePath)
+	if err == nil {
+		*manifest = manifest.Append(m)
+	}
+	if len(instance.GetSpec().GetManifests()) != 0 {
+		// If spec.manifests is not empty, it is possible that the eventing source is not available with the
+		// specified version. The user can specify the ingress link in the spec.manifests.
```
Comment (lionelvillard) [inline pkg/reconciler/knativeeventing/source/source.go:107]: is this ingress link or source link?
