### PR TITLE
Make the retry logic work to verify the Knative Serving resources

### LINKED ISSUE #105: Retry logic only tries once to verify the deployment resources of Knative serving
**Describe the bug**
The retry logic does not really retry. It only tries once to verify the knative serving resources.

**Expected behavior**
The retry logic should keep retrying until timeout.

**To Reproduce**
Run the integration tests for knative serving.

**Knative release version**
All.

**Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #105 

## Proposed Changes

* This PR fixes the issue with retry logic for Knative Serving to verify its deployment resources.
* It creates functions called `AssertKnativeDeploymentStatus`, `WaitForKnativeDeploymentState` and `IsKnativeDeploymentReady` for both serving and eventing to test the deployment resources.
* It removes the repeated code of deployment verifying and status checking.

### CODE REVIEW

File: test/resources/knativeserving.go [hunk 1]
```diff
@@ -21,8 +21,6 @@ package resources
 import (
 	"context"
 	"fmt"
```
Comment (mattmoor) [inline test/resources/knativeserving.go:23]: Format Go code:
```suggestion
	"fmt"

```
