### PR TITLE
Wait for deployments

### LINKED ISSUE #2009: Webhook dependant resources are deployed before deployments are available
**Describe the bug**

Right now a fresh install prints:
```
{"severity":"INFO","timestamp":"2025-03-06T08:31:02.4824378Z","logger":"knative-operator.manifestival","caller":"manifestival@v0.7.2/manifestival.go:208","message":"Updating","commit":"71d7c8c-dirty","knative.dev/pod":"knative-operator-5797f68df9-lmw8c","name":"knative-serving/routing-serving-certs","type":"networking.internal.knative.dev/v1alpha1, Kind=Certificate"}
{"severity":"ERROR","timestamp":"2025-03-06T08:31:02.677900778Z","logger":"knative-operator","caller":"knativeserving/reconciler.go:295","message":"Returned an error","commit":"71d7c8c-dirty","knative.dev/pod":"knative-operator-5797f68df9-lmw8c","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"0f01d0c0-8482-4980-9129-651122f20dc3","knative.dev/key":"knative-serving/knative-serving","targetMethod":"ReconcileKind","error":"failed to apply non rbac manifest: Internal error occurred: failed calling webhook \"webhook.serving.knative.dev\": failed to call webhook: Post \"https://webhook.knative-serving.svc:443/?timeout=10s\": dial tcp 10.109.239.115:443: connect: connection refused","stacktrace":"knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving.(*reconcilerImpl).Reconcile\n\tknative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go:295\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
```
Downstream we see a similar issue:
```
{"severity":"ERROR","timestamp":"2025-03-05T14:51:27.11460294Z","logger":"knative-operator","caller":"knativeserving/reconciler.go:295","message":"Returned an error","commit":"437a902","knative.dev/pod":"knative-operator-webhook-7458bff575-l6gm9","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"bcd23919-595c-40e0-9728-f6f89ff570db","knative.dev/key":"knative-serving/knative-serving","targetMethod":"ReconcileKind","error":"failed to apply non rbac manifest: Internal error occurred: failed calling webhook \"webhook.serving.knative.dev\": failed to call webhook: Post \"https://webhook.knative-serving.svc:443/?timeout=10s\": no endpoints available for service \"webhook\"","stacktrace":"knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving.(*reconcilerImpl).Reconcile\n\t/workspace/vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go:295\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:489"}
```

**Expected behavior**
Manifest install should enforce proper order and webhook dependent resources should be deployed only after webhook services are ready. 

**To Reproduce**
Steps to reproduce the behavior.
Install operator as usual and check the logs.
**Knative release version**
The Knative version, where you find this issue.

**Additional context**
Add any other context about the problem here such as proposed priority

This has caused issues in other scenarios where there was a non clean uninstall (validation webhook configs were still around) and due to the validation on deletion (Serving has that for legacy reasons), the webhook was called even if there was no deployment available.

### PR DESCRIPTION
**Pull request by skonto**
Fixes #2009 

## Proposed Changes

* Skip applying webhook resources until deployments are available. This makes sure resources can be reconciled properly and any resources depending on webhooks will be deployed after webhooks are up.

**Release Note**

```release-note
Proper order is enforced now during manifest installation.
```

### CODE REVIEW

**Comment by skonto** [comment]
```       state:
        waiting:
          message: back-off 2m40s restarting failed container=install-cni pod=istio-cni-node-wndwj_kube-system(692908a1-4a41-4cc7-b918-72f8a177f824)
          reason: CrashLoopBackOff

```

**Comment by skonto** [comment]
image

**Comment by skonto** [comment]
@houshengbo gentle ping.

File: pkg/reconciler/common/deployments.go [hunk 1]
```diff
@@ -52,7 +55,7 @@ func CheckDeployments(ctx context.Context, manifest *mf.Manifest, instance base.
 
 	if len(nonReadyDeployments) > 0 {
 		status.MarkDeploymentsNotReady(nonReadyDeployments)
-		return nil
+		return controller.NewRequeueAfter(1 * time.Second)
```
Comment (pierDipi) [inline pkg/reconciler/common/deployments.go:58]: Do we need to requeue blindly ? The controllers are setting up informers for deployments, so the resource will get requeued anyway when they change

https://github.com/knative/operator/blob/59db3c03435265f475b5eea80595f81d4aa8a0a7/pkg/reconciler/knativeeventing/controller.go#L71-L74

https://github.com/knative/operator/blob/59db3c03435265f475b5eea80595f81d4aa8a0a7/pkg/reconciler/knativeserving/controller.go#L71-L74

Comment (pierDipi) [reply pkg/reconciler/common/deployments.go:58]: and if that's not happening, then the informer handling is where we need to tweak to fix the issue

Comment (skonto) [reply pkg/reconciler/common/deployments.go:58]: I am aware of that, I wanted to make sure it happens faster in case something is slow.

Comment (skonto) [reply pkg/reconciler/common/deployments.go:58]: The other thing is that if I dont re-enqueue there and block the logic we still face the proble,

Comment (skonto) [reply pkg/reconciler/common/deployments.go:58]: These are the stages:

```
	stages := common.Stages{
		common.AppendTarget,
		ingress.AppendTargetIngress,
		security.AppendTargetSecurity,
		common.AppendAdditionalManifests,
		r.appendExtensionManifests,
		r.transform,
		manifests.Install,
		common.CheckDeployments,  // <- Make sure we are up here otherwise don't progress bellow
		common.InstallWebhookConfigs,
		common.InstallWebhookDependentResources,
		manifests.SetManifestPaths,
		common.MarkStatusSuccess,
		common.DeleteObsoleteResources(ctx, ks, r.installed),
	}
```

Comment (skonto) [reply pkg/reconciler/common/deployments.go:58]: I could add a check with a back off strategy at the controller side where the informer gets notified by deployments as well.

**Comment by skonto** [comment]
@pierDipi I removed the re-enqueue thing and now I just skip the next stages until we are up. If no deployment change happens no reconciliation will happen.

**Comment by skonto** [comment]
@houshengbo gentle ping

**Comment by houshengbo** [comment]
@skonto  I just fixed the CI issue, could you rebase this PR?

**Comment by skonto** [comment]
Sure.

File: pkg/reconciler/common/install.go [hunk 2]
```diff
@@ -22,17 +22,19 @@ import (
...
 
 var (
-	role            mf.Predicate = mf.Any(mf.ByKind("ClusterRole"), mf.ByKind("Role"))
-	rolebinding     mf.Predicate = mf.Any(mf.ByKind("ClusterRoleBinding"), mf.ByKind("RoleBinding"))
-	webhook         mf.Predicate = mf.Any(mf.ByKind("MutatingWebhookConfiguration"), mf.ByKind("ValidatingWebhookConfiguration"))
-	gatewayNotMatch              = "no matches for kind \"Gateway\""
+	role                      mf.Predicate = mf.Any(mf.ByKind("ClusterRole"), mf.ByKind("Role"))
+	rolebinding               mf.Predicate = mf.Any(mf.ByKind("ClusterRoleBinding"), mf.ByKind("RoleBinding"))
+	webhook                   mf.Predicate = mf.Any(mf.ByKind("MutatingWebhookConfiguration"), mf.ByKind("ValidatingWebhookConfiguration"))
+	webhookDependentResources mf.Predicate = mf.ByGVK(schema.GroupVersionKind{Group: "networking.internal.knative.dev", Version: "v1alpha1", Kind: "Certificate"})
```
Comment (houshengbo) [inline pkg/reconciler/common/install.go:36]: Do we need to specify `Version: "v1alpha1"` here, as it may change in future?

Comment (skonto) [reply pkg/reconciler/common/install.go]: I added a new predicate ByGK because ByGVK

```// ByGVK returns resources of a particular GroupVersionKind
func ByGVK(gvk schema.GroupVersionKind) Predicate {
	return func(u *unstructured.Unstructured) bool {
		return u.GroupVersionKind() == gvk
	}
}
```
would not work as u will have a version so I cannot leave it as empty.
