### PR TITLE
Filter the redundant resources in the target manifest

### LINKED ISSUE #508: Overwriting existing deployment resources spec.additionalManifests ends up with endless reconciling
**Describe the bug**
Leveraging spec.additionalManifests, we are able to specify the customized resources based on the default one.
If the resources in spec.additionalManifests already exist in default manifests, they should replace the default ones.
However, coming the deployment resource, the reconciling loop will keep on reconciling for ever, since the deployment will run into running-> terminating -> running... for ever.

**Expected behavior**
Reconciling loop should succeed ultimately.

**To Reproduce**
The spec.additionalManifests specifies the URL with existing deployment resources in the default manifests.

**Knative release version**
ANY supporting spec.additionalManifests.

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #508

### CODE REVIEW

File: pkg/reconciler/common/releases.go [hunk 1]
```diff
@@ -73,9 +89,13 @@ func TargetManifest(instance v1alpha1.KComponent) (mf.Manifest, error) {
 // So we return the target manifest if status.version is empty.
 func InstalledManifest(instance v1alpha1.KComponent) (mf.Manifest, error) {
 	current := instance.GetStatus().GetVersion()
+	fmt.Println("the current is ")
```
Comment (maximilien) [inline pkg/reconciler/common/releases.go:92]: Is this DEBUG statements left by mistake... I know it’s WIP

**Review by maximilien — COMMENTED** [review]
/ok-to-test

I’ll wait for WIP removal to do more thorough review.

File: pkg/reconciler/common/releases.go (hunk 1 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases.go:92]: will remove it.

File: pkg/reconciler/common/releases.go [hunk 2]
```diff
@@ -230,26 +253,29 @@ func targetManifestPath(version string, instance v1alpha1.KComponent) string {
...
+		additionalManifestPath := additionalManifestPath(version, instance)
+		pathArrayPath = strings.Join([]string{pathArrayPath, additionalManifestPath}, COMMA)
 
+	} else if len(instance.GetSpec().GetManifests()) > 0 {
+		// If spec.manifests is not empty, we leverage status.manifests
+		// to save the complete manifest path.
+		pathArrayPath = targetManifestPath(TargetVersion(instance), instance)
+	}
+	if pathArrayPath != "" {
+		return strings.Split(pathArrayPath, COMMA)
```
Comment (nak3) [inline pkg/reconciler/common/releases.go:275]: Why do we need to call `strings.Join` above and `strings.Split` here? 
Can `pathArrayPath` be string array?

File: pkg/reconciler/common/releases.go [hunk 3]
```diff
@@ -62,9 +62,22 @@ func TargetVersion(instance v1alpha1.KComponent) string {
...
+}
+
+// TargetAdditionalManifest returns the manifest for the TargetVersion specified with spec.additionalManifests.
+func TargetAdditionalManifest(instance v1alpha1.KComponent) (mf.Manifest, error) {
+	version := TargetVersion(instance)
+	additionalManifestsPath := additionalManifestPath(version, instance)
+	if additionalManifestsPath == "" {
+		return mf.Manifest{}, nil
+	}
+	return getManifestWithVersionValidation(version, additionalManifestsPath, instance)
```
Comment (nak3) [inline pkg/reconciler/common/releases.go:80]: `additionalManifestPath()` could return comma separated manifests. If `additionalManifestsPath` contains comma, `getManifestWithVersionValidation()` could work properly?

File: pkg/reconciler/common/releases_test.go [hunk 4]
```diff
@@ -731,59 +859,94 @@ func TestTargetManifest(t *testing.T) {
 				},
 			},
 		},
-		expectedNumResources: 2,
-		expectedError:        nil,
+		expectedManifestsPath: "",
+	}}
```
Comment (nak3) [inline pkg/reconciler/common/releases_test.go:863]: Can you add a test case which verifies that multiple manifest paths in `AdditionalManifests`?

File: pkg/reconciler/common/releases.go [hunk 5]
```diff
@@ -213,6 +225,17 @@ func componentDir(instance v1alpha1.KComponent) string {
 	return ""
 }
 
+func additionalManifestPath(version string, instance v1alpha1.KComponent) string {
```
Comment (nak3) [inline pkg/reconciler/common/releases.go:228]:
```suggestion
func additionalManifestPath(instance v1alpha1.KComponent) string {
```

Is it not alright without version arg? `version := TargetVersion(instance)`  should be called inside the func.
(The same commend for `targetManifestPath`.)

File: pkg/reconciler/common/releases.go (hunk 3 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases.go:80]: Yes, if there are multiple paths, `getManifestWithVersionValidation` works fine with parsing and reading them, as long as they are concatenated with comma.

File: pkg/reconciler/common/releases.go (hunk 5 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases.go:228]: done

File: pkg/reconciler/common/releases.go [hunk 6]
```diff
@@ -230,26 +253,29 @@ func targetManifestPath(version string, instance v1alpha1.KComponent) string {
...
+		// If spec.additionalManifests is not empty, we leverage status.manifests
 		// to save the complete manifest path.
-		return strings.Split(targetManifestPath(TargetVersion(instance), instance), COMMA)
-	}
+		version := TargetVersion(instance)
+		pathArrayPath = targetManifestPath(version, instance)
+		additionalManifestPath := additionalManifestPath(version, instance)
+		pathArrayPath = strings.Join([]string{pathArrayPath, additionalManifestPath}, COMMA)
 
+	} else if len(instance.GetSpec().GetManifests()) > 0 {
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/releases.go:269]: I am thinking of whether it is a good idea to ALWAYS return the path for status.manifests, no matter it is local default path, or spec.manifests, or the combination of local path and spec.additionalManifests, or even the combination of spec.manifests and spec.additionalManifests.

So far, if neither spec.additionalManifests or spec.Manifests are available, we leave it blank.

File: pkg/reconciler/common/releases.go (hunk 2 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases.go:275]: pathArrayPath itself could be a string with multiple paths, separated with comma. additionalManifestPath too.
We connect them together, and split with comma, it will end up with an array of all available paths as each item. NOT JUST pathArrayPath and additionalManifestPath, two items.

File: pkg/reconciler/common/releases_test.go (hunk 4 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases_test.go:892]: done

File: pkg/reconciler/common/releases.go [hunk 7]
```diff
@@ -230,27 +253,17 @@ func targetManifestPath(version string, instance v1alpha1.KComponent) string {
...
-	return strings.Join(urls, COMMA)
+	return manifestPath
 }
 
 func targetManifestPathArray(instance v1alpha1.KComponent) []string {
-	if len(instance.GetSpec().GetManifests()) > 0 || len(instance.GetSpec().GetAdditionalManifests()) > 0 {
-		// If either spec.manifests or spec.additionalManifests is not empty, we leverage status.manifests
-		// to save the complete manifest path.
-		return strings.Split(targetManifestPath(TargetVersion(instance), instance), COMMA)
+	pathArrayPath := targetManifestPath(instance)
```
Comment (nak3) [inline pkg/reconciler/common/releases.go:260]: `pathArrayPath` sounds strange. Also `pathArrayPath` does not have array but comma separated strings, correct?

File: pkg/reconciler/common/stages_test.go [hunk 8]
```diff
@@ -30,17 +30,184 @@ import (
...
-	util.AssertEqual(t, len(manifest.Resources()), 0)
-	stages.Execute(context.TODO(), &manifest, &v1alpha1.KnativeServing{Spec: v1alpha1.KnativeServingSpec{
-		CommonSpec: v1alpha1.CommonSpec{
-			Version: "0.16.0",
+
+	tests := []struct {
+		name                   string
+		component              v1alpha1.KComponent
+		expectedManifestsPath  string
+		expectedContainingPath string
```
Comment (nak3) [inline pkg/reconciler/common/stages_test.go:41]: `expectedContainingPath` is not used in the test.

File: pkg/reconciler/common/stages_test.go [hunk 9]
```diff
@@ -30,17 +30,184 @@ import (
...
+
+func TestStagesExecuteInstalledManifests(t *testing.T) {
+	koPath := "testdata/kodata"
+	os.Setenv(KoEnvKey, koPath)
+	defer os.Unsetenv(KoEnvKey)
+
+	testRepetition := []struct {
+		name                      string
+		component                 v1alpha1.KComponent
+		expectedContainingPath    string
```
Comment (nak3) [inline pkg/reconciler/common/stages_test.go:139]: Same with above. `expectedContainingPath` and `expectedNotContainingPath` are not used.

File: pkg/reconciler/common/releases.go (hunk 7 above)
Comment (houshengbo) [reply pkg/reconciler/common/releases.go]: I changed it into target path.

File: pkg/reconciler/common/stages_test.go (hunk 8 above)
Comment (houshengbo) [reply pkg/reconciler/common/stages_test.go]: removed.

File: pkg/reconciler/common/stages_test.go (hunk 9 above)
Comment (houshengbo) [reply pkg/reconciler/common/stages_test.go]: removed.
