### PR TITLE
Get the version number by reading the structure of kodata

### LINKED ISSUE #113: Lift the limit of reading versions from version/version.go
**Describe the bug**
Serving and eventing version are hard coded in the file version.version.go. Operator needs a way to dynamically determine a default version to install.

**Expected behavior**
The structure of kodata/knative-serving and kodata/knative-eventing can be refactored into a list of dirs, containing supported versions, under each one. We can get the version based on the dir name, and grab the manifest by reading the files under it.
The dir version will be removed.

**To Reproduce**
This is how current operator works.

**Knative release version**
All.

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #113

## Proposed Changes

* This PR creates a common function RetrieveManifestPath to get the manifest path, based on the version and component.
* Get the version number by reading the structure of kodata/knative-serving and kodata/knative-eventing.
* Remove the directory of version.

### CODE REVIEW

File: pkg/reconciler/common/read_releases_test.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package common
+
+import (
+	"context"
+	mf "github.com/manifestival/manifestival"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:21]: Format Go code:
```suggestion

```

File: pkg/reconciler/common/read_releases_test.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+	"os"
+	"testing"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:23]: Format Go code:
```suggestion
	"testing"

	mf "github.com/manifestival/manifestival"
```

File: pkg/reconciler/common/read_releases_test.go [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+
+	util "knative.dev/operator/pkg/reconciler/common/testing"
+)
+
+func TestRetrieveManifest(t *testing.T) {
+	tests := []struct {
+		component    string
+		version      string
+		label        string
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:32]: Format Go code:
```suggestion
		component string
		version   string
		label     string
```

File: pkg/reconciler/common/read_releases_test.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+	}{{
+		component:  "knative-serving",
+		version:    "0.14.0",
+		label:      "serving.knative.dev/release",
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:36]: Format Go code:
```suggestion
		component: "knative-serving",
		version:   "0.14.0",
		label:     "serving.knative.dev/release",
```

File: pkg/reconciler/common/read_releases_test.go [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+	}, {
+		component:  "knative-eventing",
+		version:    "0.14.2",
+		label:      "eventing.knative.dev/release",
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:40]: Format Go code:
```suggestion
		component: "knative-eventing",
		version:   "0.14.2",
		label:     "eventing.knative.dev/release",
```

File: pkg/reconciler/knativeeventing/controller.go [hunk 6]
```diff
@@ -15,12 +15,7 @@ package knativeeventing
 
 import (
 	"context"
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:17]: Format Go code:
```suggestion
	"context"

```

File: pkg/reconciler/knativeeventing/knativeeventing.go [hunk 7]
```diff
@@ -19,7 +19,6 @@ package knativeeventing
 import (
 	"context"
 	"fmt"
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/knativeeventing.go:21]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/knativeserving/controller.go [hunk 8]
```diff
@@ -16,19 +16,14 @@ package knativeserving
 import (
 	"context"
 	"fmt"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:18]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/common/read_releases_test.go (hunk 1 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:21]: Format Go code:
```suggestion

```

File: pkg/reconciler/common/read_releases_test.go (hunk 2 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:23]: Format Go code:
```suggestion
	"testing"

	mf "github.com/manifestival/manifestival"
```

File: pkg/reconciler/common/read_releases_test.go (hunk 3 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:32]: Format Go code:
```suggestion
		component string
		version   string
		label     string
```

File: pkg/reconciler/common/read_releases_test.go (hunk 4 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:36]: Format Go code:
```suggestion
		component: "knative-serving",
		version:   "0.14.0",
		label:     "serving.knative.dev/release",
```

File: pkg/reconciler/common/read_releases_test.go (hunk 5 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:40]: Format Go code:
```suggestion
		component: "knative-eventing",
		version:   "0.14.2",
		label:     "eventing.knative.dev/release",
```

File: pkg/reconciler/knativeeventing/controller.go (hunk 6 above)
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:17]: Format Go code:
```suggestion
	"context"

```

File: pkg/reconciler/knativeeventing/knativeeventing.go (hunk 7 above)
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/knativeeventing.go:21]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/knativeserving/controller.go (hunk 8 above)
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:18]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/knativeeventing/controller.go [hunk 9]
```diff
@@ -15,13 +15,9 @@ package knativeeventing
...
-	"os"
-	"path/filepath"
 
-	"github.com/go-logr/zapr"
-	mfc "github.com/manifestival/client-go-client"
-	mf "github.com/manifestival/manifestival"
 	"go.uber.org/zap"
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:19]: Format Go code:
```suggestion

```

File: pkg/reconciler/knativeeventing/controller.go [hunk 10]
```diff
@@ -15,13 +15,9 @@ package knativeeventing
...
+	mfc "github.com/manifestival/client-go-client"
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:20]: Format Go code:
```suggestion
	mfc "github.com/manifestival/client-go-client"
	"go.uber.org/zap"
```

File: pkg/reconciler/knativeserving/controller.go [hunk 11]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
-	"os"
-	"path/filepath"
 
 	"go.uber.org/zap"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:20]: Format Go code:
```suggestion

```

File: pkg/reconciler/knativeserving/controller.go [hunk 12]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
-
-	operatorclient "knative.dev/operator/pkg/client/injection/client"
-	kubeclient "knative.dev/pkg/client/injection/kube/client"
-	"knative.dev/pkg/injection"
-	"knative.dev/pkg/logging"
-
-	"github.com/go-logr/zapr"
 	mfc "github.com/manifestival/client-go-client"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:21]: Format Go code:
```suggestion
	mfc "github.com/manifestival/client-go-client"
	"go.uber.org/zap"
```

File: pkg/reconciler/knativeserving/controller.go [hunk 13]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
-	mf "github.com/manifestival/manifestival"
 	"k8s.io/client-go/tools/cache"
+
 	"knative.dev/operator/pkg/apis/operator/v1alpha1"
 	servingv1alpha1 "knative.dev/operator/pkg/apis/operator/v1alpha1"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:25]: Format Go code:
```suggestion
	servingv1alpha1 "knative.dev/operator/pkg/apis/operator/v1alpha1"
	operatorclient "knative.dev/operator/pkg/client/injection/client"
```

File: pkg/reconciler/knativeserving/controller.go [hunk 14]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
 	knativeServinginformer "knative.dev/operator/pkg/client/injection/informers/operator/v1alpha1/knativeserving"
 	knsreconciler "knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving"
+	operatorclient "knative.dev/operator/pkg/client/injection/client"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:28]: Format Go code:
```suggestion

```

File: pkg/reconciler/knativeserving/controller.go [hunk 15]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
 	"knative.dev/operator/pkg/reconciler"
 	"knative.dev/operator/pkg/reconciler/common"
 	servingcommon "knative.dev/operator/pkg/reconciler/knativeserving/common"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:31]: Format Go code:
```suggestion
	servingcommon "knative.dev/operator/pkg/reconciler/knativeserving/common"
	kubeclient "knative.dev/pkg/client/injection/kube/client"
```

File: pkg/reconciler/knativeserving/controller.go [hunk 16]
```diff
@@ -16,30 +16,25 @@ package knativeserving
...
 	deploymentinformer "knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment"
 	"knative.dev/pkg/configmap"
 	"knative.dev/pkg/controller"
+	kubeclient "knative.dev/pkg/client/injection/kube/client"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:35]: Format Go code:
```suggestion

```

File: pkg/reconciler/knativeeventing/controller.go [hunk 17]
```diff
@@ -15,12 +15,9 @@ package knativeeventing
 
 import (
 	"context"
-	"os"
-	"path/filepath"
 
-	"github.com/go-logr/zapr"
+
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:19]: Format Go code:
```suggestion

```

File: pkg/reconciler/knativeeventing/controller.go [hunk 18]
```diff
@@ -15,12 +15,8 @@ package knativeeventing
 
 import (
 	"context"
```
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:17]: Format Go code:
```suggestion
	"context"

```

File: pkg/reconciler/knativeserving/controller.go [hunk 19]
```diff
@@ -16,30 +16,24 @@ package knativeserving
 import (
 	"context"
 	"fmt"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:18]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/knativeeventing/controller.go (hunk 18 above)
Comment (mattmoor) [inline pkg/reconciler/knativeeventing/controller.go:17]: Format Go code:
```suggestion
	"context"

```

File: pkg/reconciler/knativeserving/controller.go [hunk 20]
```diff
@@ -16,31 +16,24 @@ package knativeserving
...
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:18]: Format Go code:
```suggestion
	"fmt"

```

File: pkg/reconciler/common/read_releases.go [hunk 21]
```diff
@@ -0,0 +1,50 @@
...
+	"github.com/go-logr/zapr"
+	mfc "github.com/manifestival/client-go-client"
+	mf "github.com/manifestival/manifestival"
+
+	"knative.dev/pkg/injection"
+	"knative.dev/pkg/logging"
+)
+
+// RetrieveManifest returns the manifest for Knative based a provided version and component
+func RetrieveManifest(ctx context.Context, version, kcomponent string) (mf.Manifest, error) {
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:34]: I c.

File: pkg/reconciler/common/read_releases_test.go [hunk 22]
```diff
@@ -0,0 +1,119 @@
...
+		label:     "eventing.knative.dev/release",
+	}}
+
+	os.Setenv(koPathEnvKey, koPath)
+	for _, test := range tests {
+		t.Run(test.component, func(t *testing.T) {
+			versionList, err := ListRelease(test.component)
+			util.AssertEqual(t, err, nil)
+
+			// Check all the avialable version under the directory of each Knative component
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:104]: Found potential misspelling(s):
```suggestion
			// Check all the available version under the directory of each Knative component
```

File: pkg/reconciler/common/read_releases_test.go [hunk 23]
```diff
@@ -0,0 +1,119 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package common
+
+import (
+	"context"
+	"fmt"
+	mf "github.com/manifestival/manifestival"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:22]: Format Go code:
```suggestion

```

File: pkg/reconciler/common/read_releases_test.go [hunk 24]
```diff
@@ -0,0 +1,119 @@
...
+	"os"
+	"path/filepath"
+	"testing"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:25]: Format Go code:
```suggestion
	"testing"

	mf "github.com/manifestival/manifestival"
```

File: pkg/reconciler/knativeserving/controller.go [hunk 25]
```diff
@@ -16,35 +16,32 @@ package knativeserving
...
 	deploymentinformer "knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment"
 	"knative.dev/pkg/configmap"
 	"knative.dev/pkg/controller"
+	"knative.dev/pkg/injection"
+	"knative.dev/pkg/logging"
 )
 
 const (
 	controllerAgentName = "knativeserving-controller"
+	kcomponent = "knative-serving"
```
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:44]: Format Go code:
```suggestion
	kcomponent          = "knative-serving"
```

File: pkg/reconciler/common/read_releases_test.go (hunk 22 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:104]: Found potential misspelling(s):
```suggestion
			// Check all the available version under the directory of each Knative component
```

File: pkg/reconciler/common/read_releases_test.go (hunk 23 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:22]: Format Go code:
```suggestion

```

File: pkg/reconciler/common/read_releases_test.go (hunk 24 above)
Comment (mattmoor) [inline pkg/reconciler/common/read_releases_test.go:25]: Format Go code:
```suggestion
	"testing"

	mf "github.com/manifestival/manifestival"
```

File: pkg/reconciler/knativeserving/controller.go (hunk 25 above)
Comment (mattmoor) [inline pkg/reconciler/knativeserving/controller.go:44]: Format Go code:
```suggestion
	kcomponent          = "knative-serving"
```

File: pkg/reconciler/common/read_releases.go [hunk 26]
```diff
@@ -0,0 +1,83 @@
...
+)
+
+// RetrieveManifestPath returns the manifest path for Knative based a provided version and component
+func RetrieveManifestPath(ctx context.Context, version, kcomponent string) string {
+	koDataDir := os.Getenv("KO_DATA_PATH")
+	return filepath.Join(koDataDir, kcomponent, version)
+}
+
+// ListRelease returns the all the available release verions available under kodata directory for Knative component.
+func ListRelease(kComponent string) ([]string, error) {
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:38]: I have added panic to replace all the errors returned.

File: pkg/reconciler/common/read_releases.go [hunk 27]
```diff
@@ -0,0 +1,83 @@
...
+		versionI := fmt.Sprintf("v%s", releaseTags[i])
+		versionJ := fmt.Sprintf("v%s", releaseTags[j])
+		return semver.Compare(versionI, versionJ) == 1
+	})
+
+	return releaseTags, nil
+}
+
+// GetLatestRelease returns the latest release tag available under kodata directory for Knative component.
+func GetLatestRelease(kcomponent string) (string, error) {
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:73]: I have added panic to replace all the errors returned.

File: pkg/reconciler/knativeeventing/controller.go [hunk 28]
```diff
@@ -52,10 +53,16 @@ func NewController(ctx context.Context, cmw configmap.Watcher) *controller.Impl
 		logger.Fatalw("Failed to remove old resources", zap.Error(err))
 	}
 
-	koDataDir := os.Getenv("KO_DATA_PATH")
-	config, err := mfc.NewManifest(filepath.Join(koDataDir, "knative-eventing", version.EventingVersion),
+	version, err := common.GetLatestRelease(kcomponent)
+	if err != nil {
+		logger.Fatalw("Error getting the version of the Manifest for knative-eventing", zap.Error(err))
+	}
+
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/knativeeventing/controller.go:60]: Removed.

File: pkg/reconciler/knativeeventing/knativeeventing.go [hunk 29]
```diff
@@ -148,7 +147,11 @@ func (r *Reconciler) ensureFinalizerRemoval(_ context.Context, _ *mf.Manifest, i
 func (r *Reconciler) install(ctx context.Context, manifest *mf.Manifest, ke *eventingv1alpha1.KnativeEventing) error {
 	logger := logging.FromContext(ctx)
 	logger.Debug("Installing manifest")
-	return common.Install(manifest, version.EventingVersion, &ke.Status)
+	version, err := common.GetLatestRelease(kcomponent)
+	if err != nil {
+		return err
+	}
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/knativeeventing/knativeeventing.go:153]: Removed

File: pkg/reconciler/knativeserving/controller.go [hunk 30]
```diff
@@ -65,10 +62,16 @@ func NewController(ctx context.Context, cmw configmap.Watcher) *controller.Impl
 		logger.Fatal(err)
 	}
 
-	koDataDir := os.Getenv("KO_DATA_PATH")
-	config, err := mfc.NewManifest(filepath.Join(koDataDir, "knative-serving", version.ServingVersion),
+	version, err := common.GetLatestRelease(kcomponent)
+	if err != nil {
+		logger.Fatalw("Error getting the version of the Manifest for knative-serving", zap.Error(err))
+	}
+
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/knativeserving/controller.go:69]: Removed

File: pkg/reconciler/knativeserving/knativeserving.go [hunk 31]
```diff
@@ -138,7 +137,11 @@ func (r *Reconciler) transform(ctx context.Context, instance *servingv1alpha1.Kn
 func (r *Reconciler) install(ctx context.Context, manifest *mf.Manifest, instance *servingv1alpha1.KnativeServing) error {
 	logger := logging.FromContext(ctx)
 	logger.Debug("Installing manifest")
-	return common.Install(manifest, version.ServingVersion, &instance.Status)
+	version, err := common.GetLatestRelease(kcomponent)
+	if err != nil {
+		return err
+	}
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/knativeserving/knativeserving.go:143]: Removed

File: pkg/reconciler/common/read_releases.go [hunk 32]
```diff
@@ -0,0 +1,83 @@
...
+	"path/filepath"
+	"sort"
+
+	"golang.org/x/mod/semver"
+)
+
+// RetrieveManifestPath returns the manifest path for Knative based a provided version and component
+func RetrieveManifestPath(ctx context.Context, version, kcomponent string) string {
+	koDataDir := os.Getenv("KO_DATA_PATH")
+	return filepath.Join(koDataDir, kcomponent, version)
```
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:34]: @jcrossley3 What do you mean by an unknown version? Is it a version that is not semantic version, or not available bundled in the image?

File: pkg/reconciler/common/read_releases.go [hunk 33]
```diff
@@ -0,0 +1,74 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package common
+
+import (
+	"fmt"
+	"golang.org/x/mod/semver"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases.go:21]: Format Go code:
```suggestion

```

File: pkg/reconciler/common/read_releases.go [hunk 34]
```diff
@@ -0,0 +1,74 @@
...
+	"io/ioutil"
+	"os"
+	"path"
+	"path/filepath"
+	"sort"
```
Comment (mattmoor) [inline pkg/reconciler/common/read_releases.go:26]: Format Go code:
```suggestion
	"sort"

	"golang.org/x/mod/semver"
```

File: pkg/reconciler/common/read_releases.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (jcrossley3) [reply pkg/reconciler/common/read_releases.go:33]: I meant unknown as in "the operator doesn't know of a valid path to a bag of yaml representing that version". I was thinking the operator would just see if `os.Stat(result)` returned an error before returning the result, just because it's easy enough to verify that the version matches an actual embedded dir. I'm not sure I'd want that behavior for non-local path, e.g. http, so we can revisit later, or if you feel strongly that we shouldn't ensure the path is valid, that's fine, too.

File: pkg/reconciler/common/read_releases.go [hunk 35]
```diff
@@ -0,0 +1,75 @@
...
+	if len(releaseTags) == 0 {
+		panic(fmt.Errorf("unable to find any version number for %s", kComponent))
+	}
+
+	// This function makes sure the versions are sorted in a descending order.
+	sort.Slice(releaseTags, func(i, j int) bool {
+		// Add the prefix "v" in front of the version
+		versionI := fmt.Sprintf("v%s", releaseTags[i])
+		versionJ := fmt.Sprintf("v%s", releaseTags[j])
+		return semver.Compare(versionI, versionJ) == 1
```
Comment (jcrossley3) [inline pkg/reconciler/common/read_releases.go:65]: I didn't realize that library was so strict about the "v" prefix. Would it make things simpler to include the "v" in the directory name?

Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:65]: We do not put the "v" in the status.version. We need to convert it either here, or checking with the status.version or even spec.version.
There are potentially three places to consider the name of the versions.
```
Dir names
status.version
even spec.version.

Do we consider changing the status.version by adding "v"?

File: pkg/reconciler/common/read_releases.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:33]: We should OK without validating the path.
When we create the manifest, it will surely returns an error, if the path we get from this function is not valid.

File: pkg/reconciler/common/read_releases.go (hunk 35 above)
Comment (jcrossley3) [reply pkg/reconciler/common/read_releases.go:65]: I don't have a strong opinion. I'm for whatever makes the code (and the user's life) simpler. I honestly thought the semver spec treated the 'v' as optional -- probably got that idea from Gopkg.toml.

Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:65]: SemVer lib takes the "v" as part of the MAJOR. It does not conform to the definition and the example here: https://semver.org/(I do not see `v` in front of all the versions). I tend to keep the format as major.minor.patch, without the letter `v` for our code.
We only add `v`, when comparing two versions.

Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:65]: I can create a function called `func isFormerVersionLater(former, latter string) bool`, to compare two versions. It adds `v`, if it is missing.

File: pkg/reconciler/common/read_releases.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (jcrossley3) [reply pkg/reconciler/common/read_releases.go:37]: Should probably have a test validating that

File: pkg/reconciler/common/read_releases.go [hunk 36]
```diff
@@ -0,0 +1,88 @@
...
+
+// ListReleases returns the all the available release versions available under kodata directory for Knative component.
+func ListReleases(kComponent string) []string {
+	releaseTags := []string{}
+	// List all the directories available under kodata
+	koDataDir := os.Getenv(KoEnvKey)
+	pathname := filepath.Join(koDataDir, kComponent)
+	fileList, err := ioutil.ReadDir(pathname)
+	if err != nil {
+		panic(err)
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases.go:59]: Why panic here? Why not return errors for structured error handling? (Applies to all errors herein)

File: pkg/reconciler/common/read_releases.go [hunk 37]
```diff
@@ -0,0 +1,88 @@
...
+func RetrieveManifestPath(version, kcomponent string) string {
+	koDataDir := os.Getenv(KoEnvKey)
+	return filepath.Join(koDataDir, kcomponent, version)
+}
+
+func isFirstVersionMoreRecent(former, latter string) bool {
+	return semver.Compare(addMissingLetterV(former), addMissingLetterV(latter)) == 1
+}
+
+func addMissingLetterV(version string) string {
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases.go:44]:
```suggestion
func sanitizeSemver(version string) string {
```

Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases.go:44]: Also: This is only used inside the compare function which is only used when listing releases. Why don't we just always create directories with correct semver versions and drop this entirely?

File: pkg/reconciler/common/read_releases.go [hunk 38]
```diff
@@ -0,0 +1,88 @@
...
+	if version == "" || version[0] == 'v' {
+		return version
+	}
+	return fmt.Sprintf("v%s", version)
+}
+
+// ListReleases returns the all the available release versions available under kodata directory for Knative component.
+func ListReleases(kComponent string) []string {
+	releaseTags := []string{}
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases.go:53]:
```suggestion
	releaseTags := make([]string, 0, len(fileList))
```

And move below.

File: pkg/reconciler/common/read_releases.go [hunk 39]
```diff
@@ -0,0 +1,88 @@
...
+		}
+	}
+	if len(releaseTags) == 0 {
+		panic(fmt.Errorf("unable to find any version number for %s", kComponent))
+	}
+
+	// This function makes sure the versions are sorted in a descending order.
+	sort.Slice(releaseTags, func(i, j int) bool {
+		// The index i is the one after the index j. If i is more recent than j, return true to swap.
+		return isFirstVersionMoreRecent(releaseTags[i], releaseTags[j])
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases.go:78]: Just inline the compare from above? The comment is more than enough to state the intent here.

File: pkg/reconciler/common/read_releases_test.go [hunk 40]
```diff
@@ -0,0 +1,111 @@
...
+	tests := []struct {
+		component string
+		expected  string
+	}{{
+		component: "knative-serving",
+		expected:  "0.14.0",
+	}, {
+		component: "knative-eventing",
+		expected:  "0.14.2",
+	}}
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases_test.go:67]: I think we need to add some actual tests here. I..e create testdata where there's more than one version and then see which one is returned?

File: pkg/reconciler/common/read_releases_test.go [hunk 41]
```diff
@@ -0,0 +1,111 @@
...
+
+	os.Setenv(KoEnvKey, koPath)
+	for _, test := range tests {
+		t.Run(test.component, func(t *testing.T) {
+			version := GetLatestRelease(test.component)
+			util.AssertEqual(t, version, test.expected)
+		})
+	}
+	os.Unsetenv(KoEnvKey)
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases_test.go:76]: defer this above?

File: pkg/reconciler/common/read_releases_test.go [hunk 42]
```diff
@@ -0,0 +1,111 @@
...
+				util.AssertEqual(t, err, nil)
+				expectedLabelValue := "v" + version
+				for _, resource := range manifest.Filter(mf.ByLabel(test.label, "")).Resources() {
+					label := resource.GetLabels()[test.label]
+					util.AssertEqual(t, label, expectedLabelValue)
+				}
+			}
+		})
+	}
+	os.Unsetenv(KoEnvKey)
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases_test.go:110]: same.

File: pkg/reconciler/common/read_releases_test.go [hunk 43]
```diff
@@ -0,0 +1,111 @@
...
+	for _, test := range tests {
+		t.Run(test.component, func(t *testing.T) {
+			version := GetLatestRelease(test.component)
+			util.AssertEqual(t, version, test.expected)
+		})
+	}
+	os.Unsetenv(KoEnvKey)
+}
+
+func TestManifestVersionTheSame(t *testing.T) {
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases_test.go:79]: Why are we testing this? Are the release labels of importance to us?

File: pkg/reconciler/common/read_releases_test.go [hunk 44]
```diff
@@ -0,0 +1,111 @@
...
+	}, {
+		component: "knative-eventing",
+		version:   "0.14.2",
+	}}
+
+	os.Setenv(KoEnvKey, koPath)
+	for _, test := range tests {
+		t.Run(test.component, func(t *testing.T) {
+			manifestPath := RetrieveManifestPath(test.version, test.component)
+			expected := fmt.Sprintf("%s/%s/%s", koPath, test.component, test.version)
```
Comment (markusthoemmes) [inline pkg/reconciler/common/read_releases_test.go:48]: This doesn't make a lot of sense to have here. The `expected` value should go into the test struct above.

File: pkg/reconciler/common/read_releases.go (hunk 36 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:59]: @markusthoemmes I took the suggestions Jim has given.
It used to return errors with this function, but we do not expect any errors, since kodata structure is defined by us.

File: pkg/reconciler/common/read_releases.go (hunk 37 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:44]: Done

Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:44]: @markusthoemmes That works for me.
However, we need to convert the version anyhow, coz we use the version without `v` to set the status version. We still need to convert the version.
To get rid of the version conversion, we need to make sure spec.version and status.version also include `v` at the beginning. Do we have to enforce users to do that?

File: pkg/reconciler/common/read_releases.go (hunk 38 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:53]: done.

File: pkg/reconciler/common/read_releases.go (hunk 39 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:78]: Done.

File: pkg/reconciler/common/read_releases.go (hunk 37 above)
Comment (markusthoemmes) [reply pkg/reconciler/common/read_releases.go:44]: Then let's consistently **not** use a `"v"` and always add it. Once we start dealing with user input, we can think about sanitizing just that but I wouldn't want to sanitize everything.

Comment (markusthoemmes) [reply pkg/reconciler/common/read_releases.go:44]: Then let's consistently **not** use a `"v"` and always add it. Once we start dealing with user input, we can think about sanitizing just that but I wouldn't want to sanitize everything.

File: pkg/reconciler/common/read_releases_test.go (hunk 44 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases_test.go:77]: done

File: pkg/reconciler/common/read_releases_test.go (hunk 40 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases_test.go:98]: I created a testdata/kodata to host a structure similar to what we will have

File: pkg/reconciler/common/read_releases.go (hunk 37 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go]: That's what I doing now. Keep x.y.z without `v`, and use it everywhere. Once we need to compare the versions, add `v` in front.

File: pkg/reconciler/common/read_releases_test.go (hunk 41 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases_test.go]: done

File: pkg/reconciler/common/read_releases_test.go (hunk 43 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases_test.go]: This is validation of yamls. We label them with a version, and use the version to check the labels one by one to see if they match. This is copied from the version_test.go.
I am not sure how important it will be. We MAY add it back later.

File: pkg/reconciler/common/read_releases.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go:37]: tests added to validate the manifest creation.

File: pkg/reconciler/common/read_releases.go (hunk 37 above)
Comment (markusthoemmes) [reply pkg/reconciler/common/read_releases.go]: It's not quite though. You're always either adding or not adding the version. Do we want users to be able to put `v0.15` and `0.15` in there? I kinda think we only want one of those to work honestly.

Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go]: If we decide to use 0.15.x all the time without `v`, how could that change the this PR? I am confused how that will affect the code here?

File: pkg/reconciler/knativeeventing/knativeeventing.go [hunk 45]
```diff
@@ -148,7 +147,7 @@ func (r *Reconciler) ensureFinalizerRemoval(_ context.Context, _ *mf.Manifest, i
 func (r *Reconciler) install(ctx context.Context, manifest *mf.Manifest, ke *eventingv1alpha1.KnativeEventing) error {
 	logger := logging.FromContext(ctx)
 	logger.Debug("Installing manifest")
-	return common.Install(manifest, version.EventingVersion, &ke.Status)
+	return common.Install(manifest, common.GetLatestRelease(kcomponent), &ke.Status)
```
Comment (markusthoemmes) [inline pkg/reconciler/knativeeventing/knativeeventing.go:150]: Why fetch this twice? I'd probably store the determined version in the reconciler's state until we actually move the manifest loading here. Same for the serving component.

File: pkg/reconciler/common/read_releases.go (hunk 37 above)
Comment (houshengbo) [reply pkg/reconciler/common/read_releases.go]: All the directories are named after the version without `v`, so `addMissingLetterV` can add it before comparison.
spec.version and status.version are without `v`, so `addMissingLetterV` can add it before comparison.
